# backend/pyproject.toml

[tool.ruff]
target-version = "py311"
line-length = 100

# Exclude the legacy backup so it doesn't gate CI.
extend-exclude = [
  "app_backup_before_gait.py",
  "**/__pycache__/**",
]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"
