name: Deploy to Render
on:
  push: { branches: [ "main" ] }
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Expose secrets as environment variables for all steps
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID_BACKEND: ${{ secrets.RENDER_SERVICE_ID_BACKEND }}
      RENDER_SERVICE_ID_WEB: ${{ secrets.RENDER_SERVICE_ID_WEB }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test (imports)
        working-directory: backend
        run: |
          python - << 'PY'
          import importlib
          for mod in ("fastapi","pydantic"):
              importlib.import_module(mod)
          print("Imports OK")
          PY

      - name: Trigger Render deploy (backend)
        run: |
          curl -fsSL \
            -H "accept: application/json" \
            -H "authorization: Bearer $RENDER_API_KEY" \
            -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID_BACKEND/deploys"

      - name: Trigger Render deploy (frontend)
        if: ${{ env.RENDER_SERVICE_ID_WEB != '' }}
        run: |
          curl -fsSL \
            -H "accept: application/json" \
            -H "authorization: Bearer $RENDER_API_KEY" \
            -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID_WEB/deploys"
